apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-basic-169632536
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-basic-169632536
    app.kubernetes.io/part-of: test-app-169632536
  name: python-basic-169632536
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python-basic-169632536
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python-basic-169632536
    spec:
      containers:
      - image: quay.io/hacdev/ow0c2ois-tenant/test-app-169632536/python-basic-169632536@sha256:ed8ab0770a137d4db1ac63e2972c214837505532d14e483f977ffc933756e883
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
